### ISSUE TITLE
Add function for change contact

### ISSUE THREAD

**Issue by mtbitcr** [BitcoinCredit/E-Bills#72]
We currently have a feature to add and remove contacts from the contact book. A contact book is a map that is written to a file. Each contact consists of two fields - name and node id. The name is the key of the map, the node id is the value.
We need to be able to change the contact (name, node id, or both fields).

**TODO:**
- [ ]  Backend function to modify a contact
- [ ]  Endpoint
- [ ]  Icon in frontend to change a contact

**Comment by MykytaTymko** [comment]
We currently have a feature to add and remove contacts from the contact book. A contact book is a map that is written to a file. Each contact consists of two fields - name and node id. The name is the key of the map, the node id is the value.
We need to be able to change the contact (name, node id, or both fields).
TODO:
- [ ] Backend function to modify a contact
- [ ] Endpoint
- [ ] Icon in frontend to change a contact
